### PR TITLE
1st commit with chapter 6 codes

### PR DESCRIPTION
**Pull request by tanjumul**
now marge my file

### CODE REVIEW

**Comment by K-2LU** [comment]
Dude, wrong repo

**Comment by tanjumul** [comment]
> Dude, wrong repo
then , where i should put it ?

**Comment by K-2LU** [comment]
https://github.com/K-2LU/CSE-233

**Comment by K-2LU** [comment]
> > Dude, wrong repo
> then , where i should put it ? 
> 

https://github.com/K-2LU/CSE-233

**Comment by tanjumul** [comment]
will do this thing tomorrow !

**Pull request closed without merging**
